### ISSUE TITLE
Providing annotations for other datasets

### ISSUE THREAD

**Issue by ChiSu001** [pixelite1201/CameraHMR#2]
Hi! Thanks for the great work!

Currently I can only find annotations for **INSTA/AIC** images. I wonder will you release fitted SMPL parameters using a  **full perspective camera** for **COCO** and **MPII** as mentioned in your paper? Thanks!

**Comment by pixelite1201** [comment]
MPII and COCO parameters are available now to download.

**Comment by ChiSu001** [comment]
Thanks!

**Comment by rihat99** [comment]
MPII and COCO parameters are currently not available on the website, the link gives the error: "Error: File not found."

**Comment by pixelite1201** [comment]
Thanks for pointing it out. Fixed the links. Now you could download them.

**Comment by pixelite1201** [comment]
There was a problem with file naming after the last update. I have fixed it and its available again now.
